### ISSUE TITLE
Cant import in spyder

### ISSUE THREAD

**Issue by DavidEic** [manaakiwhenua/pycrown#1]
Hi!

So I installed pycrown and all requirements. The test runs fine and returns no errors.
Unfortunately when I try to "from pycrown import PyCrown" in spyder I get :
cannot import name 'PyCrown' from 'pycrown' (unknown location)

How to fix this?

I am new to the coding world so please excuse me if its a stupid questions.

Thanks in advance!
David

**Comment by zjans** [comment]
solved via email

Possible solutions:
a) install Spyder in the same conda environment
b) use python interpreter from the conda environment (change Python interpreter in Spyder)
