### ISSUE TITLE
Excuse me, about PyCrown asking for help

### ISSUE THREAD

**Issue by chengzioo** [manaakiwhenua/pycrown#12]
hallo!Please forgive me for my poor English.I have had the pleasure of reading the Pycrowd-fast Raster-based Individual Tree Segmentation for LiDAR Data that you have published on GitHub.However, after preprocessing with the LAS data in your package, the following error occurs when running the code:

   Traceback (most recent call last):
   File "F:/pycrown/pycrown-master/example/example.py", line 22, in <module>
    PC = PyCrown(F_CHM, F_DTM, F_DSM, F_LAS, outpath='result')
   File "E:\py36\lib\site-packages\pycrown\pycrown.py", line 125, in __init__
    self.epsg = int(proj.GetAttrValue('AUTHORITY', 1))
   TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

   I hope you can give me some advice. Thank you very much.

**Comment by XUYIRS** [comment]
The image(s) was/were lack of projection information.

**Comment by chengzioo** [comment]
> 图像缺少投影信息。

Thank you！However, after preprocessing the data in the bag, it is still the same problem. May I leave your contact information?

**Comment by XUYIRS** [comment]
WeChat：XUYIRS
