### ISSUE TITLE
Running example.py with my own data

### ISSUE THREAD

**Issue by sweco-sekrsv** [manaakiwhenua/pycrown#3]
I have prepared my own data (attached) and just changed the inputs in the example.py. My guess is that the LAS-file need some special treatment, but I'm not sure what is needed. I get an error saying:

```
Traceback (most recent call last):
  File "example_ks.py", line 83, in <module>
    PC.crowns_to_polys_smooth(store_las=True)
  File "C:\Users\SEKRSV\AppData\Local\Continuum\miniconda3\envs\pycrown-env\lib\site-packages\pycrown-0.2-py3.6-win-amd64.egg\pycrown\pycrown.py", line 826, in crowns_to_polys_smooth
    op='within', how="inner")
  File "C:\Users\SEKRSV\AppData\Local\Continuum\miniconda3\envs\pycrown-env\lib\site-packages\geopandas\tools\sjoin.py", line 69, in sjoin
    tree_idx = rtree.index.Index(stream)
  File "C:\Users\SEKRSV\AppData\Local\Continuum\miniconda3\envs\pycrown-env\lib\site-packages\rtree\index.py", line 264, in __init__
    self.handle = self._create_idx_from_stream(stream)
  File "C:\Users\SEKRSV\AppData\Local\Continuum\miniconda3\envs\pycrown-env\lib\site-packages\rtree\index.py", line 728, in _create_idx_from_stream
    return IndexStreamHandle(self.properties.handle, stream)
  File "C:\Users\SEKRSV\AppData\Local\Continuum\miniconda3\envs\pycrown-env\lib\site-packages\rtree\index.py", line 854, in __init__
    self._ptr = self._create(*args, **kwargs)
  File "C:\Users\SEKRSV\AppData\Local\Continuum\miniconda3\envs\pycrown-env\lib\site-packages\rtree\core.py", line 29, in check_void
    raise RTreeError(msg)
rtree.core.RTreeError: Error in "Index_CreateWithStream": IllegalArgumentException: RTree::BulkLoader::bulkLoadUsingSTR: Empty data stream given.
Exception ignored in: <bound method Handle.__del__ of <rtree.index.IndexStreamHandle object at 0x0000013004AF5B70>>
Traceback (most recent call last):
  File "C:\Users\SEKRSV\AppData\Local\Continuum\miniconda3\envs\pycrown-env\lib\site-packages\rtree\index.py", line 875, in __del__
    self.destroy()
  File "C:\Users\SEKRSV\AppData\Local\Continuum\miniconda3\envs\pycrown-env\lib\site-packages\rtree\index.py", line 863, in destroy
    if self._ptr is not None:
AttributeError: 'IndexStreamHandle' object has no attribute '_ptr'
```

Any ideas?

[data_krsv.zip](https://github.com/manaakiwhenua/pycrown/files/3978991/data_krsv.zip)

**Comment by sweco-sekrsv** [comment]
I looked into this a bit more and found that if I change:
https://github.com/manaakiwhenua/pycrown/blob/b05956c556c2547bf597e9b36e9a12489a3f071f/pycrown/pycrown.py#L196
to
`self.las = self.las.assign(classification=0.)`

I get passed this error.

**Comment by zjans** [comment]
This must have been some remnant from a specific point cloud classification in one of the earlier example datasets. I removed the line completely in the recent commit: https://github.com/manaakiwhenua/pycrown/commit/66b09817aed12f846adbf16702043f1fcff8afde

I also added a convenience function to clip the trees using a simple inward buffer ... so you don't need to look up the correct bounding box anymore, e.g.: `PC.clip_trees_to_bbox(inbuf=11)`

**Comment by cass-rankine** [comment]
I'm having the process exit at the same line it looks like, running the example with my own data:

<pre>(pycrown-env) <font color="#4E9A06"><b>crankine73@crankine73</b></font>:<font color="#3465A4"><b>~/Projects/repos/pycrown/exampleChinook</b></font>$ python exampleChinook.py 
Tree crowns delineation: 0.402s
Number of trees: 10751
Tree tops corrected: 738
Tree tops corrected: 6.864477723002511%
DSM correction: 435
COM correction: 303
Converting LAS point cloud to shapely points
Converting raster crowns to shapely polygons
Attach LiDAR points to corresponding crowns
Traceback (most recent call last):
  File &quot;exampleChinook.py&quot;, line 55, in &lt;module&gt;
    PC.crowns_to_polys_smooth(store_las=True)
  File &quot;/home/crankine73/anaconda3/envs/pycrown-env/lib/python3.6/site-packages/PyCrown-0.2-py3.6-linux-x86_64.egg/pycrown/pycrown.py&quot;, line 837, in crowns_to_polys_smooth
    op=&apos;within&apos;, how=&quot;inner&quot;)
  File &quot;/home/crankine73/anaconda3/envs/pycrown-env/lib/python3.6/site-packages/geopandas/tools/sjoin.py&quot;, line 69, in sjoin
    tree_idx = rtree.index.Index(stream)
  File &quot;/home/crankine73/anaconda3/envs/pycrown-env/lib/python3.6/site-packages/rtree/index.py&quot;, line 278, in __init__
    self.handle = self._create_idx_from_stream(stream)
  File &quot;/home/crankine73/anaconda3/envs/pycrown-env/lib/python3.6/site-packages/rtree/index.py&quot;, line 1067, in _create_idx_from_stream
    return IndexStreamHandle(self.properties.handle, stream)
  File &quot;/home/crankine73/anaconda3/envs/pycrown-env/lib/python3.6/site-packages/rtree/index.py&quot;, line 1197, in __init__
    self._ptr = self._create(*args, **kwargs)
  File &quot;/home/crankine73/anaconda3/envs/pycrown-env/lib/python3.6/site-packages/rtree/core.py&quot;, line 30, in check_void
    raise RTreeError(msg)
rtree.core.RTreeError: Error in &quot;Index_CreateWithStream&quot;: IllegalArgumentException: RTree::BulkLoader::bulkLoadUsingSTR: Empty data stream given.
</pre>

Any idea how to resolve this error @zjans ?

**Comment by zjans** [comment]
@cass-rankine Not sure why I missed removing line 196 in my previous commit. Please check if it works now.

**Comment by nefuhhanrui** [comment]
Hello, how do you use your data to generate CHM, DEM and DTM? Can you tell me? Thank you very much
