### ISSUE TITLE
Filter size not an integer

### ISSUE THREAD

**Issue by BC14w** [manaakiwhenua/pycrown#4]
I've ran the example.py code using the example files, but when importing my own CHM, DSM, DTM and las files I keep getting an error in line 28 (`PC.filter_chm(5)`)
this relates to line 467 in pycrown.py. 
the exception error is:
`Filter size not an integer`
But it is. I tried to rewrite line 28 like so: `PC.filter_chm(int(5))`. 
But still doesn't work.
Do you know what could be the issue.
Thanks

**Comment by zjans** [comment]
Thank you for reporting this issue. 

What is the pixel size (in metre) of your CHM raster? 
The smoothing filter specified with `PC.filter_chm(5)` is in metres. In case your raster has a pixel size of 1.5 metre and you want to apply a 5 metre smoothing filter this would actually result in a filter with pixel size 3.33.

I'll try to update the code to make this clear - and add the option to specify the number of pixels instead of metre.

**Comment by zjans** [comment]
I've added the option to specify filter size in pixels in the newest commit:  f8cd2d4f0e3773c2c9dafb257982165c97be700d

```Python
PC.filter_chm(5, ws_in_pixels=True)
PC.tree_detection(PC.chm, ws=5, ws_in_pixels=True, hmin=16.)
```

Please let me know if this helps.

**Comment by carl-dev** [comment]
It looks like your last commit broke example.py. When I try to run it after a fresh clone it throws an error for an unexpected argument.
![image](https://user-images.githubusercontent.com/54633755/75190681-d1e06180-571e-11ea-8665-f5e7a9b2d564.png)

**Comment by zjans** [comment]
Sorry for that. The new parameter is **ws_in_pixels**. I updated the example.
Cheers

**Comment by BC14w** [comment]
I am also getting the same error with the latest commits. 
TypeError: filter_chm() got an unexpected keyword argument 'ws_in_pixels'

**Comment by BC14w** [comment]
I am also getting the same error with the latest commits. 
TypeError: filter_chm() got an unexpected keyword argument 'ws_in_pixels'

**Comment by zjans** [comment]
Did you reinstall the pycrown package after pulling the recent commit?
```
(pycrown-env) D:\git-repos\pycrown>pip uninstall pycrown
(pycrown-env) D:\git-repos\pycrown>python setup.py install
```
I just tried it in a fresh conda environment and it works for me.

**Comment by BC14w** [comment]
that fixed it. thanks a lot.
