### ISSUE TITLE
Why does _smooth_raster not allow float ws? It's possible that raster is not in full meters.

### ISSUE THREAD

**Issue by mavavilj** [manaakiwhenua/pycrown#5]
Why does _smooth_raster not allow float ws? It's possible that raster is not in full meters.

And one meter might be a big approximation.

Should I perhaps scale the raster up to non-decimal units prior to running filter_chm or _smooth_raster, or do something else?

**Comment by zjans** [comment]
Hi,

You don't need to scale your raster to a spatial resolution with an even number, but please be conscious of your raster resolution and how your pixel size relates to metre in your case.
`_smooth_raster` simply applies a median filter over an image and thus works on pixels.

`filter_chm()` takes a number (in metre) to smooth the raster. E.g. if your CHM has a resolution of 0.5m and you want to apply a 3 metre smoothing filter, you'd need to type: `filter_chm(3)` - it will then actually translate to a 6 **pixel** filter.
If you'd rather prefer to directly specify a 3 pixel smooth filter (1.5 metre), you'd need to type: `filter_chm(3, ws_in_pixels=True)`

(This is similar to `tree_detection()` which uses a maximum filter to detect tree tops.)

Cheers,
Jan
