### ISSUE TITLE
Can't not find the classification result

### ISSUE THREAD

**Issue by Elephant-C** [manaakiwhenua/pycrown#6]
Hi!

I installed pycrown and all requirements on Ubuntu 18.04, and the test runs fine without errors.
Then I executed the example by python example.py, and got all the output.
However, I can not find the classification result you show in step6 after loading the tree.las in cloudcompare.
There are only intensity and none in Scalar Field option.

How to fix this?

Thank you for your time and concern 
Yujie Cao

**Comment by zjans** [comment]
Hi,
the classification result (unique tree id) is stored in the 'intensity' field in ascending order, i.e. from 1 to the total number of trees.
It might be difficult to differentiate between trees as each tree id refers to the (very similar) colour value of the chosen colormap.

Please try the following in CloudCompare: Edit > Scalar field(s) > Convert to random RGB 
This should create a randomized colour-representation.

I hope this helps. Please let me know @Elephant-C if you have additional questions.

**Comment by Elephant-C** [comment]
thanks a lot
